#!/usr/bin/env bash
# pi-status.sh - auto-generated by pi-tmux-status extension
# Renders colored icons for each pi instance in the current tmux window.

set -euo pipefail

WINDOW_ID="${1:-}"
[[ -n "$WINDOW_ID" ]] || exit 0

DIR="/tmp"
PFX="pi-tmux-"

read_state() {
  local f="$1"
  [[ -f "$f" ]] || { echo "none"; return; }
  local state pid
  read -r state pid 2>/dev/null < "$f" || { echo "none"; return; }
  if [[ -n "$pid" && "$pid" != "0" ]] && ! kill -0 "$pid" 2>/dev/null; then
    rm -f "$f" 2>/dev/null || true
    echo "none"
    return
  fi
  echo "${state:-idle}"
}

panes=$(tmux list-panes -t "$WINDOW_ID" -F "#{pane_id} #{pane_index}" 2>/dev/null |
        sort -k2 -n | awk '{print $1}' 2>/dev/null) || panes=""

[[ -z "$panes" ]] && exit 0

icons=()
for pane in $panes; do
  f="${DIR}/${PFX}${pane}.txt"
  s=$(read_state "$f")
  case "$s" in
    working) icons+=("#[fg=colour220,blink]●#[default]") ;;
    asking)  icons+=("#[fg=colour196]●#[default]") ;;
    idle)    icons+=("#[fg=colour245]○#[default]") ;;
    *)       ;;
  esac
done

[[ ${#icons[@]} -eq 0 ]] && exit 0

printf '[%s]' "$(IFS=' '; echo "${icons[*]}")"
